# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-24 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('abstract', models.TextField(blank=True, max_length=256, verbose_name='摘要')),
                ('body', models.TextField(verbose_name='正文')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='博客插图')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '博客文章',
                'ordering': ['-created_time'],
                'verbose_name': '博客文章',
            },
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128, verbose_name='博客分类')),
            ],
            options={
                'verbose_name_plural': '博客分类',
                'verbose_name': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=128, verbose_name='博客标签')),
            ],
            options={
                'verbose_name_plural': '博客标签',
                'verbose_name': '博客标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categorys',
            field=models.ManyToManyField(to='blog.Categorys', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tags', verbose_name='标签'),
        ),
    ]
