# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-29 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page_view',
            field=models.SmallIntegerField(default=0, verbose_name='访问量'),
        ),
    ]
